### ISSUE TITLE
Return Type Break Changes Broke My Project

### ISSUE THREAD

**Issue by cary-hu** [Lusito/tsx-dom#15]
This package is awesome for tsx component, but after upgrade version from 1.3.0 to 1.4.0, The return type changed from JSX .HTMLElement to JSX.Element.

Is there any way help me to migrate from version 1.3.0 to 1.4.0.
Or
I need keep use version 1.3.0 ?

**Comment by Lusito** [comment]
Hi @cary-hu,

The type `JSX.Element` is defined as `type Element = HTMLElement | SVGElement;`. If that breaks your code, it's probably because the return type of the JSX Syntax can now be either of HTMLElement or SVGElement. You'll need to add an `as HTMLElement`; after your JSX to receive the same element type.

I'll check if I can make this configurable, so that users who don't create SVG elements with the JSX Syntax don't have to do this.

Sadly, autodetection is currently not possible: https://github.com/microsoft/TypeScript/issues/14729

**Comment by Lusito** [comment]
Can you try creating a file "jsx.d.ts" with the following content:
```ts

declare namespace JSX {
    type Element = HTMLElement;
}
```

I think this should do the trick without any other modifications of your code.

This can be in any .d.ts file, so if you already have a d.ts file for other definitions, it's fine to add it there.

**Comment by Lusito** [comment]
Thanks for the report!

**Comment by cary-hu** [comment]
So magic. but still hope there was a more official  solution, thanks for your help.

**Comment by Lusito** [comment]
@cary-hu there is now a better way to configure this with version 2, check out the configuration section of the readme:
https://github.com/Lusito/tsx-dom/tree/master/packages/tsx-dom#configuration
